site_name: Documenting Analysis Steps using Jupyter Lab
theme:
   name: material
   features:
       - content.code.copy   
   custom_dir: custom_dir/
extra_css: [extra.css]
extra_javascript: [extra.java]
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
plugins:
  - search
  - tags
  - mkpdfs:
      company: BTEP/GAU/CCR/NCI/NIH - email ncibtep@mail.nih.gov
      author: Alexandra L Emmons Ph.D. & Joe Wu Ph.D.
      design: custom_dir/report.css
  - expand-plugin 
copyright: Bioinformatics Training and Education Program
nav:
  - Class Overview: index.md
  - Class Slides: jupyter_class_insert_slides.md
  - jupyter_class.md
  - Class Data: class_data.md
